@startuml
title MES: чтение списка заказов и изменение статуса с серверным кешем ленты

actor "Оператор" as Op
participant "MES" as FE
participant "MES API" as MES
database "Redis (серверный кэш ленты/карточек)" as Redis
queue "RabbitMQ (события заказов)" as RMQ
participant "Сonsumer" as Proj
database "MES DB" as MESDB
participant "CRM API" as CRM
database "Shop DB" as ShopDB

== Чтение списка заказов ==
Op -> FE : Открыть заказы
FE -> MES : Запросить список заказов для отображения
MES -> Redis : Проверить актуальность и полноту серверного кэша ленты
alt Кэш актуален
  Redis --> MES : Предоставить подготовленный список для ответа
  MES --> FE : Вернуть список заказов для отображения
else Кэш неактуален или неполон
  MES -> MESDB : Получить актуальные данные
  MES -> Redis : Обновить серверный кэш ленты и карточек
  MES --> FE : Вернуть список заказов для отображения
end

== Изменение статуса заказа ==
Op -> FE : Измененить статус
FE -> MES : Передать команду изменить статус заказа
MES -> MESDB : Зафиксировать новый статус заказа
MES -> RMQ : Опубликовать событие об изменении статуса
MES --> FE : Подтвердить результат для интерфейса

== Распространение события и актуализация кэша ==
RMQ -> Proj : Доставить событие для актуализации данных
Proj -> Redis : Обновить серверный кэш ленты и карточек
RMQ -> CRM : Доставить событие для синхронизации с CRM
CRM -> ShopDB : Зафиксировать изменение статуса в БД

@enduml
